#!/usr/bin/php

<?php

$opt = getopt("r:");
$rel = isset($opt['r']) ? intval($opt['r']) : '1';

$arch = trim(shell_exec("arch"));

if ($arch != "x86_64") {
    die("The architecture of the operating system does not support: $arch");
}

$basedir = realpath(__DIR__.'/../..');

$cmd = "cd $basedir/deps/redis\n
    make\n
    cp -rp ./src/redis-server $basedir/bin/h5keeper-store ";
shell_exec($cmd);

$ver = file_get_contents($basedir."/src/version.go");
if (!preg_match("/VERSION\ +string\ +\=\ +\"(.*)\"/", $ver, $mat)) {
    die("Can not get version");
}
$ver = $mat[1];

$cmd = "rm -rf /tmp/h5keeper

mkdir -p /tmp/h5keeper/opt/h5keeper/bin
cp $basedir/bin/* /tmp/h5keeper/opt/h5keeper/bin/
cp $basedir/src/h5keeper /tmp/h5keeper/opt/h5keeper/bin/

mkdir -p /tmp/h5keeper/DEBIAN
cp $basedir/misc/debian/control /tmp/h5keeper/DEBIAN/

mkdir -p /tmp/h5keeper/etc/init.d
cp $basedir/misc/debian/init.d-scripts /tmp/h5keeper/etc/init.d/h5keeper
chmod +rx /tmp/h5keeper/etc/init.d/h5keeper

mkdir -p /tmp/h5keeper/opt/h5keeper/etc
cp $basedir/misc/redis/redis.conf /tmp/h5keeper/opt/h5keeper/etc/redis.conf
cp $basedir/misc/h5keeper/h5keeper.json /tmp/h5keeper/opt/h5keeper/etc/h5keeper.json

mkdir -p /tmp/h5keeper/opt/h5keeper/var

dpkg -b /tmp/h5keeper/ $basedir/h5keeper-{$ver}~lc.{$rel}_amd64.deb

rm -rf /tmp/h5keeper";

shell_exec($cmd);

die();
?>



 


