#!/usr/bin/php

<?php

$opt = getopt("r:");
$rel = isset($opt['r']) ? intval($opt['r']) : '1';

$arch = trim(shell_exec("arch"));

if ($arch != "x86_64") {
    die("The architecture of the operating system does not support: $arch");
}

$basedir = realpath(__DIR__.'/../..');

$cmd = "cd $basedir/deps/redis\n
    make\n
    cp -rp ./src/redis-server $basedir/bin/less-keeper-store ";
shell_exec($cmd);

$verctn = file_get_contents($basedir."/src/version.go");
if (!preg_match("/VERSION\ +string\ +\=\ +\"(.*)\"/", $verctn, $mat)) {
    die("Can not get VERSION");
}
$ver = $mat[1];
if (!preg_match("/RELEASE\ +string\ +\=\ +\"(.*)\"/", $verctn, $mat)) {
    die("Can not get RELEASE");
}
$rel = $mat[1];

$cmd = "rm -rf /tmp/less-keeper
mkdir -p /tmp/less-keeper/DEBIAN";
shell_exec($cmd);


$file = "{$basedir}/misc/debian/control";
$control = file_get_contents($file);
$mat = array(
    "/Version:\ +(.*?)\n/",
    "/Architecture:\ +(.*?)\n/",
);
$rep = array(
    "Version: {$ver}-{$rel}\n",
    "Architecture: amd64\n",
);
$control = preg_replace($mat, $rep, $control);
file_put_contents("/tmp/less-keeper/DEBIAN/control", $control);


$cmd = "
mkdir -p /tmp/less-keeper/opt/less/keeper/bin
cp $basedir/bin/* /tmp/less-keeper/opt/less/keeper/bin/
cp $basedir/src/less-keeper /tmp/less-keeper/opt/less/keeper/bin/

mkdir -p /tmp/less-keeper/etc/init.d
cp $basedir/misc/debian/init.d-scripts /tmp/less-keeper/etc/init.d/less-keeper
chmod +rx /tmp/less-keeper/etc/init.d/less-keeper

mkdir -p /tmp/less-keeper/opt/less/keeper/etc
cp $basedir/misc/redis/redis.conf /tmp/less-keeper/opt/less/keeper/etc/redis.conf
cp $basedir/misc/keeper/keeper.json /tmp/less-keeper/opt/less/keeper/etc/keeper.json

mkdir -p /tmp/less-keeper/opt/less/keeper/var

dpkg -b /tmp/less-keeper/ $basedir/less-keeper_{$ver}-{$rel}_d6_amd64.deb

rm -rf /tmp/less-keeper";

shell_exec($cmd);

exit(0);
