#!/bin/sh

set -eu

USER="lesskeeper"
GROUP="$USER"

chown -R $USER:$GROUP /opt/less/keeper
chmod +x /opt/less/keeper/bin/lesskeeper
chmod +x /opt/less/keeper/bin/lesskeeper-store
chmod +x /etc/init.d/lesskeeper

# Automatically added by dh_installinit
if [ -x "/etc/init.d/lesskeeper" ]; then
	update-rc.d lesskeeper defaults >/dev/null
	invoke-rc.d lesskeeper start || exit $?
fi
# End automatically added section

