#!/bin/sh

set -e

if [ "$1" = "purge" ]
then
	rm -rf /opt/less/keeper
	userdel lesskeeper
fi

# Automatically added by dh_installinit
if [ "$1" = "purge" ] ; then
	update-rc.d lesskeeper remove >/dev/null
fi
# End automatically added section

