#!/bin/bash

echo "DIRs"
find . -type d  | wc -l
echo "FILEs"
find . -type f  | wc -l
echo "LINEs"
find . -name "*.go" |xargs cat|grep -v ^$|wc -l
echo "DETAILs"
find . -type f -name "*.go" | xargs wc -l | sort -n

dirs=`find . -type d |xargs`
for dir in $dirs; do
    echo ${dir}
#    go fmt ${dir}/*.go
done
#find . -type f -name "*.go" |xargs sed -i 's/\t/    /g'


rm -f h5keeper

go build -ldflags "-w" -o h5keeper utils.go proposer.go acceptor.go cmdaction.go reply.go data.go jtloc.go main.go net.go node.go version.go

./h5keeper --prefix=/opt/src/m12/h5keeper

