#!/bin/bash

echo "DIRs"
find . -type d  | wc -l
echo "FILEs"
find . -type f  | wc -l
echo "LINEs"
find . -name "*.go" |xargs cat|grep -v ^$|wc -l
echo "DETAILs"
find . -type f -name "*.go" | xargs wc -l | sort -n

dirs=`find . -type d |xargs`
for dir in $dirs; do
    echo ${dir}
    gofmt -tabwidth=4 -tabs=false -w=true ${dir}/*.go
done


rm -f h5keeper

go build -ldflags "-w -s" -o h5keeper proposer.go acceptor.go cmdaction.go jtloc.go main.go version.go

./h5keeper --prefix=/opt/src/m12/h5keeper

